---
# mode can be either "whitelist" or "blacklist"
mode: "blacklist"

# List the commands you want to hide (for blacklist mode) or show (for whitelist mode)
commands:
  - "ban"
  - "ban-ip"
  - "banlist"
  - "deop"
  - "kick"
  - "kill"
  - "op"
  - "pardon"
  - "pardon-ip"
  - "stop"
  - "whitelist"
  - "reload"
  - "gamemode"
  - "version"
  - "op"
...
